Information Visualization project 1

* Numbers
  I used Numbers (Apple's version of spreadsheets) extensively. A
  large chunk of the work went into building different tables and
  battling with the charting system.

  I built groups based on the skills and interests of the
  subjects. The sheet with the results is called "Grouping".
  - [[https://www.icloud.com/iw/#numbers/BAIowpIkL3twMsXGkmiBG9m8lbtN8SiRb8yE/IVIS14_Project1_data][Numbers sheet (iCloud)]]
  - [[./IVIS14_Project1.numbers][Numbers sheet]]
  - [[./IVIS14_Project1.xlsx][Excel]]
  - [[./IVIS14_Project1.pdf][PDF]]
    
* Splunk Search
  I used a [[http://splunk.com][Splunk]] search to find out a bit more about the people that
  had listed two of the most popular hobbies/interests, Programming
  and Music. I found that subjects 3, 14 and 15 had these two
  interests in common. They may be an excellent group (disregarding
  their skills). I also searched and generated some other
  visualizations that wasn't really worth keeping.

  The Search results are [[./ProgrammingMusicSearch.pdf][here (pdf)]]
